/* Lexical Part */

!whitespace : ' ' | '\t' | '\n' | '\r';
whitespace: ' ' | '\t' | '\n' | '\r';
_digit: '0' - '9';
int: '1' - '9' {_digit};
float: (int | _digit) {\.} {_digit};
string: {('a' - 'z') | ('A' - 'Z') | ' '}; 
// Date in YYYY-MM-DD
date: (_digit _digit _digit _digit) - (_digit _digit) - (_digit _digit);

// Custom types

name: string;

comment: string;


/* Syntax Part */

<<
import(
    "github.com/cheerioskun/flit-go/models"
)

var fl = NewFitnessLog()
>>

log
    : {entry}


entry: 
    date '\n' 
        int '.' 

rep: int;

rep_pair: '[' rep rep ']';

weight: [('+' | '-')] float;

weight_pair: '[' weight weight ']';

set: (rep | rep_pair) '(' (weight | weight_pair) ')' '[' comment ']';

exercise: name 
