// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // int
			nil,      // string
			shift(4), // date
			nil,      // [
			nil,      // ]
			nil,      // +
			nil,      // -
			nil,      // float
			nil,      // (
			nil,      // )
			nil,      // ([
			nil,      // ])
			nil,      // empty
			nil,      // :
			nil,      // ,
			nil,      // list_num
			nil,      // =
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // ␚
			nil,          // int
			nil,          // string
			nil,          // date
			nil,          // [
			nil,          // ]
			nil,          // +
			nil,          // -
			nil,          // float
			nil,          // (
			nil,          // )
			nil,          // ([
			nil,          // ])
			nil,          // empty
			nil,          // :
			nil,          // ,
			nil,          // list_num
			nil,          // =
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // ␚, reduce: Log
			nil,       // int
			nil,       // string
			shift(4),  // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // int
			nil,      // string
			nil,      // date
			nil,      // [
			nil,      // ]
			nil,      // +
			nil,      // -
			nil,      // float
			nil,      // (
			nil,      // )
			nil,      // ([
			nil,      // ])
			nil,      // empty
			nil,      // :
			nil,      // ,
			shift(8), // list_num
			nil,      // =
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			reduce(4), // list_num, reduce: Date
			nil,       // =
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(29), // ␚, reduce: EntryList
			nil,        // int
			nil,        // string
			reduce(29), // date, reduce: EntryList
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(30), // ␚, reduce: EntryList
			nil,        // int
			nil,        // string
			reduce(30), // date, reduce: EntryList
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(26), // ␚, reduce: Exercises
			nil,        // int
			nil,        // string
			reduce(26), // date, reduce: Exercises
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(26), // list_num, reduce: Exercises
			nil,        // =
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			shift(11), // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(28), // ␚, reduce: Entry
			nil,        // int
			nil,        // string
			reduce(28), // date, reduce: Entry
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			shift(8),   // list_num
			nil,        // =
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			shift(14),  // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			shift(15),  // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(24), // ,, reduce: Settings
			nil,        // list_num
			reduce(24), // =, reduce: Settings
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			reduce(3), // string, reduce: String
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			reduce(3), // (, reduce: String
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(3), // ,, reduce: String
			nil,       // list_num
			reduce(3), // =, reduce: String
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(27), // ␚, reduce: Exercises
			nil,        // int
			nil,        // string
			reduce(27), // date, reduce: Exercises
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(27), // list_num, reduce: Exercises
			nil,        // =
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			shift(18), // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			reduce(3), // :, reduce: String
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			shift(14),  // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			shift(20),  // (
			reduce(24), // ), reduce: Settings
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(24), // ,, reduce: Settings
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(21), // ,, reduce: Settings
			nil,        // list_num
			reduce(21), // =, reduce: Settings
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			shift(23), // ,
			nil,       // list_num
			shift(24), // =
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(26), // int
			shift(28), // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(30), // +
			shift(31), // -
			shift(32), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			shift(33), // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			shift(14),  // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			shift(20),  // (
			reduce(24), // ), reduce: Settings
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(24), // ,, reduce: Settings
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			reduce(21), // ), reduce: Settings
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(21), // ,, reduce: Settings
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			shift(35), // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			shift(36), // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			shift(14), // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(39), // int
			nil,       // string
			nil,       // date
			shift(41), // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(10), // ,, reduce: SignedFloat
			nil,        // list_num
			reduce(10), // =, reduce: SignedFloat
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(2), // ,, reduce: Int
			nil,       // list_num
			reduce(2), // =, reduce: Int
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(19), // ,, reduce: Setting
			nil,        // list_num
			reduce(19), // =, reduce: Setting
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(3), // ,, reduce: String
			nil,       // list_num
			reduce(3), // =, reduce: String
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(20), // ,, reduce: Setting
			nil,        // list_num
			reduce(20), // =, reduce: Setting
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(26), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(30), // +
			shift(31), // -
			shift(32), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(26), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(30), // +
			shift(31), // -
			shift(32), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(9), // ,, reduce: SignedFloat
			nil,       // list_num
			reduce(9), // =, reduce: SignedFloat
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(47), // int
			shift(49), // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(51), // +
			shift(52), // -
			shift(53), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			shift(54), // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			shift(36), // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(23), // ,, reduce: Settings
			nil,        // list_num
			reduce(23), // =, reduce: Settings
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			shift(14), // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(22), // ,, reduce: Settings
			nil,        // list_num
			reduce(22), // =, reduce: Settings
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // ␚, reduce: Reps
			nil,       // int
			nil,       // string
			reduce(5), // date, reduce: Reps
			reduce(5), // [, reduce: Reps
			nil,       // ]
			reduce(5), // +, reduce: Reps
			nil,       // -
			nil,       // float
			reduce(5), // (, reduce: Reps
			nil,       // )
			reduce(5), // ([, reduce: Reps
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			reduce(5), // list_num, reduce: Reps
			nil,       // =
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: Int
			nil,       // int
			nil,       // string
			reduce(2), // date, reduce: Int
			reduce(2), // [, reduce: Int
			nil,       // ]
			reduce(2), // +, reduce: Int
			nil,       // -
			nil,       // float
			reduce(2), // (, reduce: Int
			nil,       // )
			reduce(2), // ([, reduce: Int
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			reduce(2), // list_num, reduce: Int
			nil,       // =
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(13), // ␚, reduce: Weights
			nil,        // int
			nil,        // string
			reduce(13), // date, reduce: Weights
			reduce(13), // [, reduce: Weights
			nil,        // ]
			reduce(13), // +, reduce: Weights
			nil,        // -
			nil,        // float
			shift(57),  // (
			nil,        // )
			shift(58),  // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(13), // list_num, reduce: Weights
			nil,        // =
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(60), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(17), // ␚, reduce: SetList
			nil,        // int
			nil,        // string
			reduce(17), // date, reduce: SetList
			nil,        // [
			nil,        // ]
			reduce(17), // +, reduce: SetList
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(17), // list_num, reduce: SetList
			nil,        // =
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(25), // ␚, reduce: Exercise
			nil,        // int
			nil,        // string
			reduce(25), // date, reduce: Exercise
			nil,        // [
			nil,        // ]
			shift(61),  // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(25), // list_num, reduce: Exercise
			nil,        // =
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(7), // ,, reduce: SignedFloat
			nil,       // list_num
			reduce(7), // =, reduce: SignedFloat
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(8), // ,, reduce: SignedFloat
			nil,       // list_num
			reduce(8), // =, reduce: SignedFloat
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			reduce(10), // ), reduce: SignedFloat
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(10), // ,, reduce: SignedFloat
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			reduce(2), // ), reduce: Int
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(2), // ,, reduce: Int
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			reduce(19), // ), reduce: Setting
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(19), // ,, reduce: Setting
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			reduce(3), // ), reduce: String
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(3), // ,, reduce: String
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			reduce(20), // ), reduce: Setting
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(20), // ,, reduce: Setting
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(47), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(51), // +
			shift(52), // -
			shift(53), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(47), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(51), // +
			shift(52), // -
			shift(53), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			reduce(9), // ), reduce: SignedFloat
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(9), // ,, reduce: SignedFloat
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			reduce(23), // ), reduce: Settings
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(23), // ,, reduce: Settings
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			reduce(22), // ), reduce: Settings
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			reduce(22), // ,, reduce: Settings
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(15), // ␚, reduce: Comment
			nil,        // int
			nil,        // string
			reduce(15), // date, reduce: Comment
			shift(64),  // [
			nil,        // ]
			reduce(15), // +, reduce: Comment
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(15), // list_num, reduce: Comment
			nil,        // =
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(67), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(69), // +
			shift(70), // -
			shift(71), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(73), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(75), // +
			shift(76), // -
			shift(77), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(79), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			reduce(2), // int, reduce: Int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(39), // int
			nil,       // string
			nil,       // date
			shift(41), // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			reduce(7), // ), reduce: SignedFloat
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(7), // ,, reduce: SignedFloat
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			reduce(8), // ), reduce: SignedFloat
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			reduce(8), // ,, reduce: SignedFloat
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			shift(82), // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(16), // ␚, reduce: Set
			nil,        // int
			nil,        // string
			reduce(16), // date, reduce: Set
			nil,        // [
			nil,        // ]
			reduce(16), // +, reduce: Set
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(16), // list_num, reduce: Set
			nil,        // =
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			reduce(10), // ), reduce: SignedFloat
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			reduce(2), // ), reduce: Int
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			shift(83), // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(67), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(69), // +
			shift(70), // -
			shift(71), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(67), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(69), // +
			shift(70), // -
			shift(71), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			reduce(9), // ), reduce: SignedFloat
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			reduce(10), // int, reduce: SignedFloat
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			reduce(10), // +, reduce: SignedFloat
			reduce(10), // -, reduce: SignedFloat
			reduce(10), // float, reduce: SignedFloat
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			reduce(2), // int, reduce: Int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			reduce(2), // +, reduce: Int
			reduce(2), // -, reduce: Int
			reduce(2), // float, reduce: Int
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(87), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(89), // +
			shift(90), // -
			shift(91), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(73), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(75), // +
			shift(76), // -
			shift(77), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(73), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(75), // +
			shift(76), // -
			shift(77), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			reduce(9), // int, reduce: SignedFloat
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			reduce(9), // +, reduce: SignedFloat
			reduce(9), // -, reduce: SignedFloat
			reduce(9), // float, reduce: SignedFloat
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			shift(94), // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			reduce(2), // ], reduce: Int
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(18), // ␚, reduce: SetList
			nil,        // int
			nil,        // string
			reduce(18), // date, reduce: SetList
			nil,        // [
			nil,        // ]
			reduce(18), // +, reduce: SetList
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(18), // list_num, reduce: SetList
			nil,        // =
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			shift(95), // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			reduce(3), // ], reduce: String
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(11), // ␚, reduce: Weights
			nil,        // int
			nil,        // string
			reduce(11), // date, reduce: Weights
			reduce(11), // [, reduce: Weights
			nil,        // ]
			reduce(11), // +, reduce: Weights
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(11), // list_num, reduce: Weights
			nil,        // =
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			reduce(7), // ), reduce: SignedFloat
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			reduce(8), // ), reduce: SignedFloat
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // int
			nil,        // string
			nil,        // date
			nil,        // [
			nil,        // ]
			nil,        // +
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			reduce(10), // ]), reduce: SignedFloat
			nil,        // empty
			nil,        // :
			nil,        // ,
			nil,        // list_num
			nil,        // =
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			reduce(2), // ]), reduce: Int
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			shift(96), // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(87), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(89), // +
			shift(90), // -
			shift(91), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			shift(87), // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			shift(89), // +
			shift(90), // -
			shift(91), // float
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			reduce(9), // ]), reduce: SignedFloat
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			reduce(7), // int, reduce: SignedFloat
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			reduce(7), // +, reduce: SignedFloat
			reduce(7), // -, reduce: SignedFloat
			reduce(7), // float, reduce: SignedFloat
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			reduce(8), // int, reduce: SignedFloat
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			reduce(8), // +, reduce: SignedFloat
			reduce(8), // -, reduce: SignedFloat
			reduce(8), // float, reduce: SignedFloat
			nil,       // (
			nil,       // )
			nil,       // ([
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // ␚, reduce: Reps
			nil,       // int
			nil,       // string
			reduce(6), // date, reduce: Reps
			reduce(6), // [, reduce: Reps
			nil,       // ]
			reduce(6), // +, reduce: Reps
			nil,       // -
			nil,       // float
			reduce(6), // (, reduce: Reps
			nil,       // )
			reduce(6), // ([, reduce: Reps
			nil,       // ])
			nil,       // empty
			nil,       // :
			nil,       // ,
			reduce(6), // list_num, reduce: Reps
			nil,       // =
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(14), // ␚, reduce: Comment
			nil,        // int
			nil,        // string
			reduce(14), // date, reduce: Comment
			nil,        // [
			nil,        // ]
			reduce(14), // +, reduce: Comment
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(14), // list_num, reduce: Comment
			nil,        // =
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(12), // ␚, reduce: Weights
			nil,        // int
			nil,        // string
			reduce(12), // date, reduce: Weights
			reduce(12), // [, reduce: Weights
			nil,        // ]
			reduce(12), // +, reduce: Weights
			nil,        // -
			nil,        // float
			nil,        // (
			nil,        // )
			nil,        // ([
			nil,        // ])
			nil,        // empty
			nil,        // :
			nil,        // ,
			reduce(12), // list_num, reduce: Weights
			nil,        // =
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			reduce(7), // ]), reduce: SignedFloat
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // int
			nil,       // string
			nil,       // date
			nil,       // [
			nil,       // ]
			nil,       // +
			nil,       // -
			nil,       // float
			nil,       // (
			nil,       // )
			nil,       // ([
			reduce(8), // ]), reduce: SignedFloat
			nil,       // empty
			nil,       // :
			nil,       // ,
			nil,       // list_num
			nil,       // =
		},
	},
}
