// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 40: // ['(','(']
			return 2
		case r == 41: // [')',')']
			return 3
		case r == 43: // ['+','+']
			return 4
		case r == 44: // [',',',']
			return 5
		case r == 45: // ['-','-']
			return 6
		case r == 48: // ['0','0']
			return 7
		case 49 <= r && r <= 57: // ['1','9']
			return 8
		case r == 58: // [':',':']
			return 9
		case r == 61: // ['=','=']
			return 10
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case r == 91: // ['[','[']
			return 12
		case r == 93: // [']',']']
			return 13
		case 97 <= r && r <= 122: // ['a','z']
			return 11
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 91: // ['[','[']
			return 14
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		case 48 <= r && r <= 57: // ['0','9']
			return 16
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		case 48 <= r && r <= 57: // ['0','9']
			return 17
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 18
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 11
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 41: // [')',')']
			return 20
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 21
		case 48 <= r && r <= 57: // ['0','9']
			return 22
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 57: // ['0','9']
			return 24
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 57: // ['0','9']
			return 25
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 18
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 11
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 18
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		case 65 <= r && r <= 90: // ['A','Z']
			return 11
		case 97 <= r && r <= 122: // ['a','z']
			return 11
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 22
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 22
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 57: // ['0','9']
			return 26
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 57: // ['0','9']
			return 27
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 28
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 57: // ['0','9']
			return 29
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 28
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 31
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 57: // ['0','9']
			return 29
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 23
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 32
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 33
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 34
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
